spring:
  redis:
    host: 123.56.7.121
#    host: 127.0.0.1
    password: rd0U.p57RqZ!7e
    database: 15
  datasource:
    url: jdbc:mysql://5628e0ad1c559.sh.cdb.myqcloud.com:9993/virgo?useSSL=true&serverTimezone=GMT%2B8
    username: cdb_outerroot
    password: Vsl88402_uuY6
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      max-lifetime: 10
      connection-test-query: SELECT 1
      maximum-pool-size: 50
  data:
    mongodb:
#      uri: mongodb://admin:UmVvsINhf03dko42@127.0.0.1:27017/virgo-exam?authSource=admin&maxPoolSize=200
      uri: mongodb://admin:UmVvsINhf03dko42@123.56.7.121:27017/virgo-exam?authSource=admin&maxPoolSize=200
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  boot:
    admin:
      client:
        url: http://141.164.49.58:8866
        instance:
          prefer-ip: true
          service-url: http://123.56.7.121:8002
management:
  endpoints:
    web:
      exposure:
        include: "*"